#include <stdlib.h>
#include <stdio.h>
#include <string>
#include <sstream>
#include <fstream>
#include <vector>
#include <ctype.h>
#include <math.h>
#include <memory>

#include <QElapsedTimer>
#include <QFile>
#include <QFileDialog>
#include <QtOpenGL/QGLWidget>
#include <QMessageBox>
#include <QPainter>
#include <QKeyEvent>
#include <QThread>
#include <QTimer>
